---
- name: Download MongoDB GPG key
  get_url:
    url: "{{ gpg_key_ubuntu_src }}"
    dest: "{{ gpg_keyfile_ubuntu_dest }}"
    mode: '0644'

- name: Add MongoDB GPG key to apt
  apt_key:
    key_file: "{{ gpg_keyfile_ubuntu_dest }}"
    state: present

- name: Create MongoDB repository file
  copy:
    content: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
    dest: "{{ mongodb_filepath }}"
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: "{{ mongodb_package_name }}"
    state: present
    update_cache: yes


