---
- name: Download MongoDB GPG key
  get_url:
    url: "{{ gpg_key_ubuntu_src }}"
    dest: "{{ gpg_keyfile_ubuntu_dest }}"
    mode: '0644'

- name: Import MongoDB GPG key
  become: true
  shell: "apt-key add {{ gpg_keyfile_ubuntu_dest }}"

- name: Create MongoDB repository file
  become: true
  copy:
    content: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
    dest: "{{ mongodb_filepath }}"
    mode: '0644'

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install MongoDB
  become: true
  apt:
    name: "{{ mongodb_package_name }}"
    state: present
    update_cache: yes
