---
- name: MongoDB - Import public key
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
- name: MongoDB - Add repository
  become: true
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
    repo: 'deb <a href="http://repo.mongodb.org/apt/ubuntu">http://repo.mongodb.org/apt/ubuntu</a> xenial/mongodb-org/3.2 multiverse'
    state: present
    update_cache: yes
- name: MongoDB - Install MongoDB
  become: true
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
- name: MongoDB - Running state
  become: true
  service:
    name: mongod
    state: started
