---

- name: Create | Collection | Creates a database
  shell: mongosh --eval 'use gllzmembers1';
  
- name: Create | Collection | Creates first collection
  shell: mongosh gllzmembers1 --eval 'db.createCollection("members");'
  
  
- name: Create and Add | Collection and documents | Creates first collection and adds documents to it
  shell: mongosh gllzmembers1 --eval 'db.members.insertMany([{"name":"Tarini"},{"name":"Srisharan"},{"name":"Bharat"},{"name":"Yamini"},{"name":"Ashok"},{"name":"Saranya"},{"name":"Sreehari"}])';
