---

- name: install mysql
  become: yes
  yum:
    name: mysql-server
    state: present
    
- name: Install pip for Python 3
  become: yes
  package:
     name: python3-pip
     state: present
    
- name: Install Required pip modules
  become: yes
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3
    

  
    
- name: Start MySQL service
  become: yes
  service:
    name: mysqld
    state: started
